
Loading encoders weights from irse50!
Loading decoder weights from pretrained!
Loading MOCO model from path: pretrained_models/moco_v2_800ep_pretrain.pt
Loading dataset for cloth_encode
Number of training samples: 14000
Number of test samples: 4000
torch.Size([4, 3, 4, 4])
torch.Size([4, 3, 8, 8])
torch.Size([4, 3, 16, 16])
torch.Size([4, 3, 32, 32])
torch.Size([4, 3, 64, 64])
torch.Size([4, 3, 128, 128])
torch.Size([4, 3, 4, 4])
torch.Size([4, 3, 8, 8])
torch.Size([4, 3, 16, 16])
torch.Size([4, 3, 32, 32])
torch.Size([4, 3, 64, 64])
torch.Size([4, 3, 128, 128])
Metrics for train, step 0
	loss_l2 =  0.23357704281806946
	loss_lpips =  0.8239957094192505
	loss_moco =  0.6417193412780762
	id_improve =  -0.33894388005137444
	loss_adv =  0.1732867956161499
	loss =  1.130232334136963
/data/shijianyang/code/pixel2style2pixel/training/ranger.py:123: UserWarning: This overload of addcmul_ is deprecated:
	addcmul_(Number value, Tensor tensor1, Tensor tensor2)
Consider using one of the following signatures instead:
	addcmul_(Tensor tensor1, Tensor tensor2, *, Number value) (Triggered internally at  /opt/conda/conda-bld/pytorch_1616554800319/work/torch/csrc/utils/python_arg_parser.cpp:1005.)
  exp_avg_sq.mul_(beta2).addcmul_(1 - beta2, grad, grad)
Traceback (most recent call last):
  File "/home/shijianyang/anaconda3/envs/py37torch18/lib/python3.7/site-packages/PIL/Image.py", line 2813, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 1), '|u1')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "training/train.py", line 32, in <module>
    main()
  File "training/train.py", line 28, in main
    coach.train()
  File "./training/coach.py", line 160, in train
    self.wb_logger.log_images_to_wandb(x, r_rgb, y, y_hat, id_logs, prefix="train", step=self.global_step, opts=self.opts)
  File "/data/shijianyang/code/pixel2style2pixel/training/utils/wandb_utils.py", line 39, in log_images_to_wandb
    wandb.Image(common.log_input_image(x[i], opts)),
  File "/data/shijianyang/code/pixel2style2pixel/training/utils/common.py", line 10, in log_input_image
    return tensor2im(x)
  File "/data/shijianyang/code/pixel2style2pixel/training/utils/common.py", line 23, in tensor2im
    return Image.fromarray(var.astype('uint8'))
  File "/home/shijianyang/anaconda3/envs/py37torch18/lib/python3.7/site-packages/PIL/Image.py", line 2815, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey) from e
TypeError: Cannot handle this data type: (1, 1, 1), |u1